name: Greetings

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    name: Greet First-Time Contributors
    runs-on: ubuntu-latest

    steps:
      - name: Greet first-time issue creator
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Thanks for opening your first issue! We appreciate your contribution to TypeScript Utility Types.

            A maintainer will review your issue soon. In the meantime:
            - Make sure you've provided all the requested information
            - Check if there are any similar existing issues
            - Feel free to ask questions if anything is unclear

            Welcome to the community! 🎉
          pr-message: |
            🎉 Thanks for opening your first pull request! We're excited to review your contribution.

            Before we can merge, please make sure:
            - [ ] All tests pass (`npm test`)
            - [ ] Linting passes (`npm run lint`)
            - [ ] You've added tests for new functionality
            - [ ] Documentation is updated if needed
            - [ ] Your commits follow [Conventional Commits](https://www.conventionalcommits.org/)

            A maintainer will review your PR soon. Thanks for contributing! 🚀
